<?php

use Illuminate\Database\Seeder;

class CancelScholarshipTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cancel_scholarships')->insert(
            [
                [
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'other_reason' => Str::random(50),
                    'scholarship_reason_id' => rand(1, 3),
                    'register_scholarship_id' => rand(1, 285),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 3,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],
            ]
        );
    }
}
