<?php

use Illuminate\Database\Seeder;

class LanguageScholarshipTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('register_scholarships')->insert(
            [
                [
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],[
                    'user_id' => rand(1, 230),
                    'country_id' => rand(1, 184),
                    'university_id' => rand(1, 6),
                    'college_id' => rand(1, 22),
                    'status_id' => rand(1, 3),
                    'reject_reason' => Str::random(80),
                    'registeration_type_id' => 6,
                    'created_by' => rand(1, 230),
                    'created_at' => date("Y-m-d H:i:s", rand(1262055681,1334567899)),
                ],
            ]
        );
    }
}
